<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
	<!-- Integration of test framework adapters with test environment (Visual Studio, dotnet CLI) -->
	<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
	<!-- Integration of test framework adapters with test environment (Visual Studio, dotnet CLI) -->

	<!-- NUnit -->
	<PackageReference Include="NUnit"             Version="4.6.1"  />
	<PackageReference Include="NUnit.Analyzers"   Version="4.14.0" />
	<PackageReference Include="NUnit3TestAdapter" Version="6.2.0"  />
	<!-- NUnit -->

	<!-- Integration of PostgreSQL Docker containers with test environment (Visual Studio, dotnet CLI) -->
	<PackageReference Include="Testcontainers.PostgreSql" Version="4.14.0" />
	<!-- Integration of PostgreSQL Docker containers with test environment (Visual Studio, dotnet CLI) -->

	<!-- Data Access Layer -->
	<PackageReference Include="Dapper" Version="2.1.79" />
	<!-- Data Access Layer -->
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="..\Npgsql.Tvp\Npgsql.Tvp.csproj" />
  </ItemGroup>

  <ItemGroup>
	<None Include="Init\*">
	  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	</None>
	<None Include="Data\*">
	  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	</None>
  </ItemGroup>

</Project>