name: dotnet package

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'
          source-url: https://nuget.pkg.github.com/<owner>/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}'


      - name: Display dotnet version
        run: dotnet --version


      - name: Install dependencies
        run: dotnet restore

        
      - name: Build
        run: dotnet build --configuration Release


      - name: Publish the package to GPR
        run: dotnet nuget push */**/*.nupkg